// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl3QWJHuy-JNYAESKIRcrOX2zpyV5ksyo',
    appId: '1:616138192390:web:b6cc253ecd25c32fe27587',
    messagingSenderId: '616138192390',
    projectId: 'electohub-bca',
    authDomain: 'electohub-bca.firebaseapp.com',
    storageBucket: 'electohub-bca.firebasestorage.app',
    measurementId: 'G-N79D60FZNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvQEkclughEtTsZ7r9rmobV5ByABHbM0o',
    appId: '1:616138192390:android:43e0c47dd5be2fe3e27587',
    messagingSenderId: '616138192390',
    projectId: 'electohub-bca',
    storageBucket: 'electohub-bca.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZCTZy04mvAltYt-8AC5d4y_gGnSsPfAI',
    appId: '1:616138192390:ios:557a0fdf17cc7a46e27587',
    messagingSenderId: '616138192390',
    projectId: 'electohub-bca',
    storageBucket: 'electohub-bca.firebasestorage.app',
    iosBundleId: 'com.example.eVotingApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZCTZy04mvAltYt-8AC5d4y_gGnSsPfAI',
    appId: '1:616138192390:ios:557a0fdf17cc7a46e27587',
    messagingSenderId: '616138192390',
    projectId: 'electohub-bca',
    storageBucket: 'electohub-bca.firebasestorage.app',
    iosBundleId: 'com.example.eVotingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl3QWJHuy-JNYAESKIRcrOX2zpyV5ksyo',
    appId: '1:616138192390:web:bed9316e3ce41d54e27587',
    messagingSenderId: '616138192390',
    projectId: 'electohub-bca',
    authDomain: 'electohub-bca.firebaseapp.com',
    storageBucket: 'electohub-bca.firebasestorage.app',
    measurementId: 'G-42Q7LXJ3KR',
  );

}